options:
  docker: true


pipelines:
  custom:
    build:
     - step:
        name: Build
        image: winie/qt-android-build
        script:
            - qmake
            - make
            - mkdir _result
            - make install INSTALL_ROOT=./_result/
            - cp android-libtestAndroid.so-deployment-settings.json android-libbuild.so-deployment-settings.json
            - androiddeployqt --output _result --verbose --gradle
            - ls -la ./
            - ls -la ./_bin/
            - ls -la ./_result/
        artifacts:
            - _bin/**
            - _result/**