options:
  docker: true


pipelines:
  custom:
    build:
     - step:
        name: Build
        image: winie/qt-android-build
        script:
            - qmake
            - make
            - mkdir _result
            - mkdir _install
            - make install
            - androiddeployqt --output _result
            - ls -la ./
            - ls -la ./_bin/
            - ls -la ./_result/
        artifacts:
            - _bin/**
            - _install/**
            - _result/**